name: CI DigitalOcean

on:
  push:
    branches:
      - master
  
jobs:
  build:
    env:
      IMAGE: boomzero/dailycookies
      K8S_CLUSTER: k8s-learning-dailycookies
      K8S_NAMESPACE: dailycookies

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${K8S_CLUSTER}

    - name: Set image tag
      run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | head -c7)" >> $GITHUB_ENV
    - name: Build container image
      run: docker build -t ${IMAGE}:${{ env.IMAGE_TAG }} -t ${IMAGE}:latest .
    - name: Push container image
      run: docker push ${IMAGE} --all-tags

    - name: Update deployment file
      run: sed -i 's|${IMAGE}:latest|${IMAGE}:${{ env.IMAGE_TAG }}|g' $GITHUB_WORKSPACE/deploy/web-deployment.yml
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl -n ${K8S_NAMESPACE} apply -f $GITHUB_WORKSPACE/deploy/web-deployment.yml
    - name: Verify deployment
      run: kubectl -n ${K8S_NAMESPACE} rollout status deployment/dailycookies
