on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      run: echo "hello world"
      # with:
      #   token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}