name: CI DigitalOcean

on:
  push:
    branches:
      - master
  
jobs:
  build:
    env:
      IMAGE: boomzero/dailycookies

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build container image
      run: docker build -t ${IMAGE}:$(echo $GITHUB_SHA | head -c7) -t ${IMAGE}:latest .
